backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://www.linke-im-westend.tk/
logo_url: https://www.linke-im-westend.tk/logo-frames/logo-f0.svg
# publish_mode: editorial_workflow
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    preview_path: "{{slug}}"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string" ,required: true}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
#     - {label: "Position", name: "pos", widget: "number", value_type: "int"}
      - {
        label: "Gehört zu Thema", name: "category", widget: "relation", 
        collection: "categories", searchFields: ["name"], valueField: "name", multiple: true
        }  
      - {label: "Autor", name: "author", widget: "relation", 
        collection: "members", searchFields: ["name"], valueField: "name"
      }
      - {label: "Veröffentlicht am", name: "date", widget: "datetime"}
      - {label: "Bild", name: "featureImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      
      
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string" ,required: true}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Kurz Beschreibung", name: "description", widget: "markdown"}

  - name: "members"
    label: "Mitglieder"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string" , required: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Gruppe", name: "group", widget: "relation",
       collection: "groups", searchFields: ["name"], valueField: "name", multiple: true, required: true}
      - {label: "Ist Autor", name: "isAuthor", widget: "boolean", required: true}
      - {label: "Kurz Beschreibung", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "groups"
    label: "Gruppe"
    folder: "content/groups"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string" ,required: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Ist Autor", name: "isAuthor", widget: "boolean", required: true}
      - {label: "Kurz Beschreibung", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "termine"
    label: "Termine und Veranstaltungen"
    folder: "content/termine"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Beginn", name: "startdate", widget: "datetime"}
      - {label: "Ende", name: "enddate", widget: "datetime"}
      - {label: "Ort", name: "ort", widget: "string"}
      - {label: "Ist Veranstaltung", name: "isEvent", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
